name: crud_rest_api_shelf
description: A simple CRUD REST API built with Dart Shelf
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.0
  drift: ^2.29.0
  path: ^1.9.0
  sqlite3: ^2.9.3
  mailer: ^6.5.0

dev_dependencies:
  build_runner: ^2.9.0
  drift_dev: ^2.29.0
  lints: ^6.0.0
  test: ^1.25.6
